/// Authentication routes
pub mod auth;
/// Bear routes
pub mod bears;
/// Can routes
pub mod cans;
/// Minigame routes
pub mod minigames;
/// Song routes
pub mod songs;
/// User routes
pub mod user;
