//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

pub mod api_keys;
pub mod cans;
pub mod connected_youtube_accounts;
pub mod cooldown;
pub mod discord_role_connections;
pub mod favourite_songs;
pub mod minigame_history;
pub mod permissions;
pub mod played_songs;
pub mod radio_state;
pub mod role_permissions;
pub mod roles;
pub mod server_channel_config;
pub mod server_config;
pub mod server_role_config;
pub mod slcb_currency;
pub mod slcb_rank;
pub mod song_requests;
pub mod song_tags;
pub mod songs;
pub mod songs_fulltext;
pub mod user_permissions;
pub mod users;
