//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

pub use super::api_keys::Entity as ApiKeys;
pub use super::cans::Entity as Cans;
pub use super::connected_youtube_accounts::Entity as ConnectedYoutubeAccounts;
pub use super::cooldown::Entity as Cooldown;
pub use super::favourite_songs::Entity as FavouriteSongs;
pub use super::permissions::Entity as Permissions;
pub use super::played_songs::Entity as PlayedSongs;
pub use super::role_permissions::Entity as RolePermissions;
pub use super::roles::Entity as Roles;
pub use super::server_channel_config::Entity as ServerChannelConfig;
pub use super::server_config::Entity as ServerConfig;
pub use super::server_role_config::Entity as ServerRoleConfig;
pub use super::slcb_currency::Entity as SlcbCurrency;
pub use super::slcb_rank::Entity as SlcbRank;
pub use super::song_requests::Entity as SongRequests;
pub use super::song_tags::Entity as SongTags;
pub use super::songs::Entity as Songs;
pub use super::songs_fulltext::Entity as SongsFulltext;
pub use super::user_permissions::Entity as UserPermissions;
pub use super::user_roles::Entity as UserRoles;
pub use super::users::Entity as Users;
