//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, serde :: Deserialize)]
#[sea_orm(table_name = "songs_fulltext")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub song_id: String,
    pub title: String,
    pub artist: String,
    pub album: String,
    #[sea_orm(column_type = "custom(\"tsvector\")", nullable)]
    pub tsvector: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
