//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;
use serde::Deserialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub watched_time: i64,
    pub boonbucks: i32,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub last_message_sent: Option<DateTime>,
    pub migrated: bool,
    pub username: Option<String>,
    pub role: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::api_keys::Entity")]
    ApiKeys,
    #[sea_orm(has_many = "super::cans::Entity")]
    Cans,
    #[sea_orm(has_many = "super::connected_youtube_accounts::Entity")]
    ConnectedYoutubeAccounts,
    #[sea_orm(has_one = "super::discord_role_connections::Entity")]
    DiscordRoleConnections,
    #[sea_orm(has_many = "super::favourite_songs::Entity")]
    FavouriteSongs,
    #[sea_orm(has_many = "super::minigame_history::Entity")]
    MinigameHistory,
    #[sea_orm(
        belongs_to = "super::roles::Entity",
        from = "Column::Role",
        to = "super::roles::Column::Name",
        on_update = "NoAction",
        on_delete = "SetDefault"
    )]
    Roles,
    #[sea_orm(has_many = "super::user_permissions::Entity")]
    UserPermissions,
}

impl Related<super::api_keys::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApiKeys.def()
    }
}

impl Related<super::cans::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Cans.def()
    }
}

impl Related<super::connected_youtube_accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ConnectedYoutubeAccounts.def()
    }
}

impl Related<super::discord_role_connections::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscordRoleConnections.def()
    }
}

impl Related<super::favourite_songs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FavouriteSongs.def()
    }
}

impl Related<super::minigame_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MinigameHistory.def()
    }
}

impl Related<super::roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Roles.def()
    }
}

impl Related<super::user_permissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserPermissions.def()
    }
}

impl Related<super::permissions::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_permissions::Relation::Permissions.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_permissions::Relation::Users.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
